---
deployment:
  tasks:
    - export DEPLOYPATH=~/public_html/
    - /bin/cp -R ~/opss/admin $DEPLOYPATH
    - /bin/cp -R ~/opss/catalog $DEPLOYPATH
    - /bin/cp -R ~/opss/image $DEPLOYPATH
    - /bin/cp -R ~/opss/system $DEPLOYPATH
    - /bin/cp -R ~/opss/system/library $DEPLOYPATH/system/library
    - /bin/cp -R ~/opss/vqmod $DEPLOYPATH
    - /bin/cp ~/opss/index.php $DEPLOYPATH
    - /bin/cp ~/opss/php.ini $DEPLOYPATH
    - php ~/deploy/deploy_script.php