---
deployment:
  tasks:
    - export DEPLOYPATH=`cat ~/deploy/deploy_path`
    - /bin/cp -fR ~/opss/admin $DEPLOYPATH
    - /bin/cp -fR ~/opss/catalog $DEPLOYPATH
    - /bin/cp -fR ~/opss/image $DEPLOYPATH
    - /bin/cp -fR ~/opss/system $DEPLOYPATH
    - /bin/cp -fR ~/opss/system/library $DEPLOYPATH/system/library
    - /bin/cp -f ~/opss/index.php $DEPLOYPATH
    - /bin/cp -f ~/opss/php.ini $DEPLOYPATH
    - /bin/cp -f ~/opss/.htaccess $DEPLOYPATH
    - /bin/cp -fR ~/opss/vqmod $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/vqmod/vqcache/*
    - /bin/rm -f $DEPLOYPATH/vqmod/checked.cache
    - /bin/rm -f $DEPLOYPATH/vqmod/mods.cache
    - php ~/deploy/deploy_script.php